<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MercatoApplication\MercatoApplication.csproj" />
    <ProjectReference Include="..\MercatoDomain\MercatoDomain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Persistence\Context\" />
    <Folder Include="Persistence\Configuration\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
